### ISSUE TITLE
请教candidate2的作用, 以及二进制文件的endian形式

### ISSUE THREAD

**Issue by chen-chao** [hhggit/mschxudp#1]
感谢您的这个工具. 这个向您请教两个问题, 算不上issue.
1. candidate2 这个参数有作用吗? 我在使用时只随便填了一个数.
2. 在我的机器上查看导出的mschxudp都是little endian, 我看到python默认使用的是处理器的endian形式. 所以如果mschxudp 在不同endian的机器里dump同一个文件, 结果会不一样吗?

**Comment by hhggit** [comment]
1.candidate字段的两个字节表示短语在候选框的位置和频度。看自己使用习惯，常用的位置排靠前一点，频度设高一点。我自己导的时候也是比较随意的，全部都用的5和7
2.所有字段都是用的小端序，因为基本都是用的小端机器，脚本里面没有特意去指定（算是一个潜在的bug吧）

**Comment by chen-chao** [comment]
嗯嗯, 好的, 非常感谢. 我用这个把ibus的字库转到微软拼音了, 非常方便.
